### PR TITLE
feat: add typevar to enable better subclassing

### PR DESCRIPTION
**Pull request by cdce8p**

### CODE REVIEW

**Comment by MartinHjelmare** [comment]
Can you give an example how it will be used?

**Comment by cdce8p** [comment]
> Can you give an example how it will be used?

As context, I was originally working on https://github.com/home-assistant/core/pull/75477 when I discovered this. Home Assistant itself subclasses `BluetoothServiceInfo` (although it isn't an issue in this particular instance since `from_advertisement` is overwritten).

**Example**
Say we create a new subclass with additional attributes and / or methods **without** overwriting `from_advertisement`.
```py
@dataclass
class SubClass(BluetoothServiceInfo):
    some_attr: int = 10

    def some_method(self, var: int) -> None: ...
```

Calling `from_advertisement` on `SubClass` will return an instance of `BluetoothServiceInfo` and not actually `SubClass`. Thus accessing `some_attr` or `some_method` will cause type errors.
```py
info = SubClass.from_advertisement(...)
reveal_type(info)  # BluetoothServiceInfo
info.some_method(2)  # type error
```

The solution for it is to use a TypeVar bound to the base class as done here. Once mypy supports [PEP 673](https://peps.python.org/pep-0673/), `typing.Self` can be used instead.

--
It's usually not necessary to update the typing if everything still works. There are a few [similar cases in Home Assistant](https://github.com/home-assistant/core/blob/2022.7.5/homeassistant/components/input_text/__init__.py#L207-L213), for example. However, since this is an external library any update will take longer than changing just HA alone which is why I openned the PR.

**Review by bdraco — APPROVED** [review]
I'm assuming this came about when you saw the with Bleak version.

**Comment by bdraco** [comment]
Would like to get Martin a chance to comment before merging anything

**Comment by cdce8p** [comment]
> I'm assuming this came about when you saw the with Bleak version.

Yeah, although not (yet) necessary. Good practice, especially in a library, never the less.

**Comment by cdce8p** [comment]
> Would like to get Martin a chance to comment before merging anything

https://github.com/home-assistant/core/pull/75477 is independent from this one. So there isn't any rush.
@bdraco Would you mind approving the workflow run? I would like to see if the commit message is fine now 😃

**Review by MartinHjelmare — APPROVED** [review]
Thanks for the explanation and example! 👍

**Comment by MartinHjelmare** [comment]
I think the commit message should use a lowercase letter after the colon.

**Comment by cdce8p** [comment]
> I think the commit message should use a lowercase letter after the colon.

Thanks! Let's see if it works now.

**Comment by cdce8p** [comment]
Forgot about it earlier, an example where using TypeVars does make a difference: https://github.com/home-assistant/core/pull/75472

**Pull request merged**
